/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrophiesRouteImport } from './routes/trophies'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlayRouteImport } from './routes/play'
import { Route as MatchRouteImport } from './routes/match'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as IndexRouteImport } from './routes/index'

const TrophiesRoute = TrophiesRouteImport.update({
  id: '/trophies',
  path: '/trophies',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/database': typeof DatabaseRoute
  '/draft': typeof DraftRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/match': typeof MatchRoute
  '/play': typeof PlayRoute
  '/settings': typeof SettingsRoute
  '/trophies': typeof TrophiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/database': typeof DatabaseRoute
  '/draft': typeof DraftRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/match': typeof MatchRoute
  '/play': typeof PlayRoute
  '/settings': typeof SettingsRoute
  '/trophies': typeof TrophiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/database': typeof DatabaseRoute
  '/draft': typeof DraftRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/match': typeof MatchRoute
  '/play': typeof PlayRoute
  '/settings': typeof SettingsRoute
  '/trophies': typeof TrophiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/database'
    | '/draft'
    | '/leaderboards'
    | '/match'
    | '/play'
    | '/settings'
    | '/trophies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection'
    | '/database'
    | '/draft'
    | '/leaderboards'
    | '/match'
    | '/play'
    | '/settings'
    | '/trophies'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/database'
    | '/draft'
    | '/leaderboards'
    | '/match'
    | '/play'
    | '/settings'
    | '/trophies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  DatabaseRoute: typeof DatabaseRoute
  DraftRoute: typeof DraftRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  MatchRoute: typeof MatchRoute
  PlayRoute: typeof PlayRoute
  SettingsRoute: typeof SettingsRoute
  TrophiesRoute: typeof TrophiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trophies': {
      id: '/trophies'
      path: '/trophies'
      fullPath: '/trophies'
      preLoaderRoute: typeof TrophiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  DatabaseRoute: DatabaseRoute,
  DraftRoute: DraftRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  MatchRoute: MatchRoute,
  PlayRoute: PlayRoute,
  SettingsRoute: SettingsRoute,
  TrophiesRoute: TrophiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
